name: Build and deploy JAR app to Azure Web App - wipi-cake-backend

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Gradle
        run: gradle clean build --no-daemon

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          # path 생략 → 기본값인 $GITHUB_WORKSPACE 로 풀립니다.

      - name: list all JARs
        run: |
          echo "JAR 파일 위치 확인"
          find . -type f -name '*.jar' | sed 's/^/  /'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: wipi-cake-backend
          slot-name: Production
          package: '**/*.jar'       # 여기서 workspace 어디에 있든 JAR을 찾습니다.
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_470D0DB7D756455CAE96377781125570 }}
