name: Build and deploy JAR app to Azure Web App - wipi-cake

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Gradle
        run: gradle clean build --no-daemon

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: build/libs

      - name: Rename downloaded Jar to app.jar
        run: |
          mv build/libs/*-SNAPSHOT.jar app.jar

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_65C78A62ED2B45A2B082BE53554D2B68 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0156D80C76EB4219A676948785DE5767 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0D97944EE3A04951ACBB7E6F5C294F04 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wipi-cake'
          slot-name: 'Production'
          package: 'app.jar'
          startup-command: 'java -jar /home/site/wwwroot/app.jar --server.port=80'
